kind: pipeline
name: default

steps:
- name: frontend
  image: croissong/verdun-ci:frontend
  pull: always
  environment:
    DOCKER_USER:
      from_secret: DOCKER_USER
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DEPLOY_KEY_B64:
      from_secret: DEPLOY_KEY_B64
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  commands:
    - sleep 10
    - python3 .ci/ci.py

services:
  - name: docker
    image: 'docker:dind'
